<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFqvBied\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFqvBied/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFqvBied.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFqvBied\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFqvBied\App_KernelDevDebugContainer([
    'container.build_hash' => 'FqvBied',
    'container.build_id' => '7ba7c615',
    'container.build_time' => 1654688561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFqvBied');
