<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPgaal3a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPgaal3a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPgaal3a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPgaal3a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPgaal3a\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pgaal3a',
    'container.build_id' => 'e3f25846',
    'container.build_time' => 1651563025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPgaal3a');
