<?php

namespace ContainerX7lst41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartenariatControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PartenariatController' shared autowired service.
     *
     * @return \App\Controller\PartenariatController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PartenariatController.php';

        $container->services['App\\Controller\\PartenariatController'] = $instance = new \App\Controller\PartenariatController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\PartenariatController', $container));

        return $instance;
    }
}
